### ISSUE TITLE
Shaking the phone while a tweakable app is in the background will bring that app's tweak window on top.

### ISSUE THREAD

**Issue by hofmanntm** [MindSea/ShakyTweaksAndroid#19]
If the tweaks demo app is installed, plus another App (App B) that uses tweaks, then this can be reproduced.
Open first App B, then go to your home screen and open the tweaks demo. Now shake the device, and the tweaks from both the apps will appear. 

The order in which they appear isn't always the same, so it might be worth switching between the app repeatedly and shaking the phone. This should reveal the problem.

**Comment by CodeFusion** [comment]
In addition, multiple layers of ShakyTweaks can pile up in the background

**Comment by gianei** [comment]
Fixed in #23
